### ISSUE TITLE
Error when importing tools

### ISSUE THREAD

**Issue by LWserenic** [thomasnguyen92/MIMIC-IV-ICD-data-processing#6]
Hello, so I tried to run the code and stumble into a problem where I cannot import it from learn and when I check this learn library it contains no tools. Is learn a custom library built or I need to install something else? Thank you
![image](https://github.com/thomasnguyen92/MIMIC-IV-ICD-data-processing/assets/167731670/3a879245-4236-4ec1-a36c-39dd8258cfa7)

**Comment by schlevik** [comment]
hi @LWserenic

This repository is for preparing the datasets only, please refer to the `README.MD` file.

We use the same format as MIMIC-III, which allows you to reproduce the MIMIC-III baselines from their respective repos accordingly, e.g. CAML.

As an example, here's a repo that reproduces the MSMN model on MIMIC-IV:

https://github.com/ASUS-AICS/ICD-MSMN

Hope that helps!

**Comment by LWserenic** [comment]
Hello @schlevik, the problem was I cannot even run the notebook mentioned in the README.MD because the said dependency isn't there. So far I can blend both repo as one and try to run the notebook. At least please mentioned where people can find the dependencies if they choose to run the notebook as is.

Anyway, thank you for the answer.
